/*
 * Глобальные настройки ReSemiClip по префиксу карт
 */

# semiclip (0 / 1) - Статус работы плагина
# 1 = Включить прозрачность
semiclip = 1;

# team (0 / 1 / 2 / 3) - На какие команды распространяется прозрачность
# 3 = Только сквозь своих союзников (Люди сквозь Людей, Зомби сквозь Зомби)
# Это исключит проход зомби сквозь людей в нычках!
team = 3;

# time (число секунд) - Время действия прозрачности с начала раунда
# 3 = Прозрачность выключится строго через 3 секунды после старта раунда
time = 3;

# crouch (0 / 1) - Проход сквозь присевших игроков в эти 3 секунды
# 1 = Можно беспрепятственно проходить сквозь сидячих игроков
crouch = 1;

# effects (0 / 1) - Визуальный эффект призрака
# 1 = Моделька игрока становится полупрозрачной
effects = 1;

# distance (число в юнитах) - Дистанция начала прозрачности
distance = 200;

# transparency (число от 0 до 255) - Плотность моделек
transparency = 130;

# penetfire (0 / 1) - Прострел сквозь игроков в эти 3 секунды
# 1 = Пули пролетают сквозь союзников
penetfire = 1;