/*
 * Персональные настройки ReSemiClip для карты Dust 2
 */

# semiclip (0 / 1) - Статус работы прозрачности на этой карте
# 0 = Полностью выключить плагин на Dust 2
# 1 = Включить плагин (игроки смогут проходить друг сквозь друга)
semiclip = 1;

# team (0 / 1 / 2 / 3) - Кто сквозь кого может проходить
# 0 = Все сквозь всех (Люди сквозь Зомби, Зомби сквозь Людей)
# 1 = Проходить можно только сквозь игроков команды Террористов (Зомби)
# 2 = Проходить можно только сквозь игроков команды Контр-Террористов (Людей)
# 3 = Только сквозь СОЮЗНИКОВ (Люди сквозь Людей, Зомби сквозь Зомби). Защищает нычки от прорыва зомби!
team = 3;

# time (число секунд) - Время действия эффекта со старта раунда
# 0 = Прозрачность работает постоянно, весь раунд без ограничений
# Любое другое число (например, 3) = Эффект выключится ровно через 3 секунды после начала раунда
time = 3;

# crouch (0 / 1) - Проход сквозь присевших игроков (в течение этих 3 секунд)
# 0 = Сидячий игрок на спавне заблокирует проход (сквозь него нельзя пройти)
# 1 = Можно свободно проходить сквозь сидячих игроков, никто никого не зажмет
crouch = 1;

# effects (0 / 1) - Визуальное отображение «призрака»
# 0 = Модельки игроков остаются обычными, плотными, даже когда стоишь внутри них
# 1 = Моделька игрока плавно становится полупрозрачной, когда ты заходишь в её текстуру
effects = 1;

# distance (число в юнитах) - На каком расстоянии моделька начинает исчезать
# Задает радиус в игровом пространстве, при приближении на который включается прозрачность. Стандарт: 200.
distance = 200;

# transparency (от 0 до 255) - Степень прозрачности «призрака»
# 0 = Игрок становится абсолютно невидимым (сквозная пустота)
# 255 = Игрок остается полностью непрозрачным, как обычная стена
# 130 = Оптимальный баланс: силуэт игрока четко виден, но он не перекрывает обзор экрана
transparency = 130;

# penetfire (0 / 1) - Прострел сквозь игроков (в течение этих 3 секунд)
# 0 = Пули будут застревать в телах союзников на спавне
# 1 = Пули летят насквозь через своих игроков (урон союзникам не наносится, но летит дальше во врагов)
penetfire = 1;