; ===================================================================
;        AMX Mod X - Меню быстрых действий над игроком для админа
; ===================================================================

"Кикнуть игрока"         "amx_kick #%userid%"          "b"     "u"    ; Полный выброс игрока с сервера
"Сделать Зомби"          "zp_zombie #%userid%"         "bd"    "u"    ; Принудительно заразить выбранного человека
"Сделать Человеком"      "zp_human #%userid%"          "bd"    "u"    ; Принудительно излечить выбранного зомби
"Возродить игрока"       "zp_respawn #%userid%"        "bd"    "u"    ; Моментально заспавнить игрока посреди раунда
"Дать 10 аммо-паков"     "zp_ammo_give #%userid% 10"   "bd"    "u"    ; Выдать мелкий бонус игроку на покупку оружия