; ===================================================================
;        AMX Mod X - Меню быстрых команд сервера для админа
; ===================================================================

"Перезапустить раунд"    "rg_round_respawn"    "a"     "u"    ; Мягкий рестарт раунда через ReAPI без багов мода
"Главное меню ZP"        "zp_menu"             "b"     "u"    ; Открыть главное меню Zombie Plague прямо из админки
"Поставить на паузу"     "amx_pause"           "ad"  		  ; Полная заморозка игрового процесса сервера