; ===================================================================
;        AMX Mod X - Меню быстрой смены настроек сервера для админа
; ===================================================================
; Формат: "<Название>" "<Команда>" "<Флаг_выполнения>" "<Флаг_админа>"
; Флаги: "a" - выполнить от имени консоли сервера, "d" - вернуть админа в меню.

"Запустить перезапуск"       "restart"                                    "a"   "u"   ; Мгновенный рестарт текущей карты
"Включить полную тьму"       "zp_lighting a;amx_say [Режим] Полная тьма"  "a"   "u"   ; Перевод освещения в режим ночи
"Включить сумерки"           "zp_lighting d;amx_say [Режим] Сумерки"      "a"   "u"   ; Стандартное мрачное освещение ZP
"Включить светлый день"      "zp_lighting m;amx_say [Режим] Светлый день" "a"   "u"   ; Обычный дневной свет на карте
"Стандартный конфиг"         "exec server.cfg"                            "a"   "u"   ; Принудительно перезагрузить server.cfg