; ===================================================================
;         AMX Mod X - Системные пути и глобальные настройки ядра
; ===================================================================

; Папка для логов ошибок плагинов
amxx_logs       addons/amxmodx/logs
; Папка со всеми конфигурациями (.cfg, .ini)
amxx_configsdir addons/amxmodx/configs
; Папка хранения баз данных и бинарных файлов
amxx_datadir    addons/amxmodx/data
; Путь к списку модулей сервера
amxx_modules    addons/amxmodx/configs/modules.ini
; Путь к списку плагинов сервера
amxx_plugins    addons/amxmodx/configs/plugins.ini
; Папка со скомпилированными плагинами (.amxx)
amxx_pluginsdir addons/amxmodx/plugins	
; Папка с бинарниками модулей (.dll, .so)
amxx_modulesdir addons/amxmodx/modules
; Файл настроек базового хранилища
amxx_vault      addons/amxmodx/data/vault.ini

; --- ГЛОБАЛЬНЫЕ НАСТРОЙКИ СЕРВЕРА ---
amxx_logging    1
; Режим логирования (1 — один файл лога в день)
mysql_timeout   0
; Время ожидания ответа MySQL (0 — защита от лагов)
bin_logging     49
; Уровень детальности бинарных логов ядра
max_binlog_size 20
; Максимальный размер бинарного лога в мегабайтах
optimizer       7
; Флаги оптимизации плагинов под процессор
disableflagman  0
; Менеджер флагов админ-команд (0 — включен)