; ===================================================================
;        AMX Mod X - Меню быстрой настройки кваров для админа
; ===================================================================

"mp_timelimit"        "0" "20" "30" "40"    "u"    ; Время игры на карте в минутах
"sv_password"         "" "123" "test"       "u"    ; Установка пароля на сервер (пустые кавычки — убрать)
"sv_voiceenable"      "0" "1"               "u"    ; Включение или полное отключение голосового чата
"mp_chattime"         "3" "5" "10"          "u"    ; Время задержки чата в секундах после конца карты
"mp_logmessages"      "0" "1"               "u"    ; Запись логов чата и действий сервера в файлы
"allow_spectators"    "0" "1"               "u"    ; Разрешить или запретить игрокам заходить за наблюдателей
"mp_freezetime"       "0" "2" "5"           "u"    ; Заморозка игроков на респавне перед началом раунда