# ========================================================
# 	ГЛАВНЫЙ КОНФИГ RESEMICLIP (ОБЩИЕ НАСТРОЙКИ СЕРВЕРА)
# ========================================================

# semiclip (0 / 1) - Статус работы прозрачности
# 0 = Полностью выключить плагин на сервере по умолчанию
# 1 = Включить прозрачность (игроки смогут проходить друг сквозь друга)
semiclip = 1;

# team (0 / 1 / 2 / 3) - На какие команды распространяется прозрачность
# 0 = Смешанный режим: проходить можно вообще сквозь всех (Люди сквозь Зомби тоже)
# 1 = Прозрачность работает только для команды Террористов (Зомби)
# 2 = Прозрачность работает только для команды Контр-Террористов (Людей)
# 3 = Прозрачность работает ТОЛЬКО ДЛЯ СОЮЗНИКОВ (Люди сквозь Людей, Зомби сквозь Зомби)
# РЕКОМЕНДАЦИЯ ДЛЯ ЗОМБИ: Оставляем "3", чтобы зомби не пролетали сквозь людей в нычках!
team = 3;

# time (число секунд от 0 до 180) - Время действия эффекта со старта раунда
# 0 = Прозрачность работает ПОСТОЯННО и без ограничений весь раунд
# Любое другое число (например, 15) = Эффект полностью отключится через 15 секунд после начала раунда
# РЕКОМЕНДАЦИЯ ДЛЯ ЗОМБИ: Раз мы в локальных картах выставили 3 секунды, здесь тоже можно поставить "3", чтобы на всех остальных картах правила не ломали баланс.
time = 3;

# crouch (0 / 1) - Автоматизация приседания и подсадок
# 0 = Игроки не могут проходить сквозь присевшего союзника
# 1 = Игроки могут проходить сквозь сидячих, а также запрыгивать на них сверху (для подсадок в нычки)
crouch = 1;

# effects (0 / 1) - Визуальный эффект прозрачности от дистанции
# 0 = Выключить эффект: модельки игроков всегда остаются обычными, плотными
# 1 = Включить эффект: плотность модельки будет плавно меняться в зависимости от расстояния между игроками
effects = 0;

# distance (число от 64 до 250) - Дистанция активации прозрачности
# Радиус в игровых юнитах, внутри которого игроки начинают проходить друг сквозь друга. Стандарт: 200.
distance = 200;

# transparency (число от 0 до 255) - Плотность модельки при прозрачности
# 0 = Игрок становится абсолютно невидимым (пустота), когда ты в него заходишь
# 255 = Игрок остается полностью плотным, как обычная стена
# 120 = Слегка прозрачный силуэт (оптимально для обзора)
transparency = 120;

# penetfire (0 / 1) - Разрешить пулям пролетать сквозь "прозрачных" союзников
# 0 = Блокировать пули телами (выстрелы будут застревать в союзниках)
# 1 = Пули будут пролетать насквозь через тиммейтов и наносить урон врагам за их спинами
penetfire = 0;